# Generated by Django 4.2.1 on 2023-09-23 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_register_email_alter_register_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegetablesInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(max_length=50)),
                ('mobile', models.TextField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('vegetable_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images/Farmer/Vegetables')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.register')),
            ],
        ),
        migrations.CreateModel(
            name='MachineInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=50)),
                ('machine_name', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=255)),
                ('mobile', models.TextField(max_length=50)),
                ('owner_address', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rent', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images/Admin/Machines')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.register')),
            ],
        ),
        migrations.CreateModel(
            name='LandInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(max_length=50)),
                ('mobile', models.TextField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rent', models.IntegerField()),
                ('others', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images/Farmer/Lands')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.register')),
            ],
        ),
    ]
