# Generated by Django 4.2.1 on 2023-09-23 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vegetablesinfo_machineinfo_landinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegetablesRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requester_name', models.CharField(max_length=50)),
                ('mobile', models.TextField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_vegetables', to='api.register')),
                ('requester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.register')),
                ('vegetables_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vegetablesinfo')),
            ],
        ),
        migrations.CreateModel(
            name='MachineRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(max_length=50)),
                ('mobile', models.TextField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rent', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_machine', to='api.register')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.register')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.machineinfo')),
            ],
        ),
        migrations.CreateModel(
            name='LandRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('mobile', models.TextField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('cost', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_land', to='api.register')),
                ('land_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.register')),
            ],
        ),
    ]
