# Generated by Django 4.2.1 on 2023-09-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vegetablesrequests_machinerequests_landrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetablesrequests',
            name='quantity',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
    ]
