# Generated by Django 4.2.1 on 2023-09-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_vegetablesrequests_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetablesrequests',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
