# Generated by Django 4.2.1 on 2023-09-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contsctus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contsctus',
            new_name='Contactus',
        ),
    ]
